ckeditor5.plugin.ckeditor_ai_agent_ai_agent:
  type: mapping
  label: 'CKEditor AI Agent'
  mapping:
    api_key:
      type: string
      label: 'API Key'
      nullable: true
    model:
      type: string
      label: 'AI Model'
      nullable: true
    endpoint_url:
      type: string
      label: 'Endpoint URL'
      nullable: true
    temperature:
      type: float
      label: 'Temperature'
      nullable: true
    max_tokens:
      type: integer
      label: 'Max Tokens'
      nullable: true
    timeout_duration:
      type: integer
      label: 'Timeout Duration'
      nullable: true
    retry_attempts:
      type: integer
      label: 'Retry Attempts'
      nullable: true
    debug_mode:
      type: boolean
      label: 'Debug Mode'
      nullable: true
    stream_content:
      type: boolean
      label: 'Stream Content'
      nullable: true
