ckeditor5.plugin.ckeditor_ai_agent_ai_agent:
  type: mapping
  label: 'CKEditor AI Agent'
  mapping:
    aiAgent:
      type: mapping
      label: 'AI Agent Settings'
      mapping:
        key_provider:
          type: string
          label: 'API Key Provider'
        apiKey:
          type: string
          label: 'API Key'
        engine:
          type: string
          label: 'AI Engine'
        model:
          type: string
          label: 'AI Model'
        ollamaModel:
          type: string
          label: 'Ollama Model'
        endpointUrl:
          type: string
          label: 'Endpoint URL'
        contentScope:
          type: string
          label: 'Content Scope'
        temperature:
          type: float
          label: 'Temperature'
        maxOutputTokens:
          type: integer
          label: 'Max Output Tokens'
        maxInputTokens:
          type: integer
          label: 'Max Input Tokens'
        contextSize:
          type: integer
          label: 'Context Size'
        editorContextRatio:
          type: float
          label: 'Editor Context Ratio'
        timeOutDuration:
          type: integer
          label: 'Timeout Duration'
        retryAttempts:
          type: integer
          label: 'Retry Attempts'
        debugMode:
          type: boolean
          label: 'Debug Mode'
        streamContent:
          type: boolean
          label: 'Stream Content'
        showErrorDuration:
          type: integer
          label: 'Show Error Duration'
        moderationEnable:
          type: boolean
          label: 'Enable Moderation'
        moderationKey:
          type: string
          label: 'Moderation Key'
        toneOfVoiceVocabulary:
          type: string
          label: 'Tone of Voice Vocabulary'
        defaultToneOfVoice:
          type: string
          label: 'Default Tone of Voice'
        tonesDropdown:
          type: sequence
          label: 'Tones Dropdown'
          sequence:
            type: mapping
            label: 'Tone Item'
            mapping:
              title:
                type: string
                label: 'Tone Title'
              command:
                type: string
                label: 'Tone Command'
        promptSettings:
          type: mapping
          label: 'Prompt Settings'
          mapping:
            overrides:
              type: sequence
              label: 'Prompt Overrides'
              sequence:
                type: string
            additions:
              type: sequence
              label: 'Prompt Additions'
              sequence:
                type: string