ckeditor5.plugin.ckeditor_ai_agent_ai_agent:
  type: mapping
  label: 'CKEditor AI Agent settings'
  mapping:
    api_key:
      type: string
      label: 'API Key'
      nullable: true
    model:
      type: string
      label: 'AI Model'
      nullable: true
    endpoint_url:
      type: string
      label: 'Endpoint URL'
      nullable: true
    temperature:
      type: float
      label: 'Temperature'
      nullable: true
    max_output_tokens:
      type: integer
      label: 'Max Output Tokens'
      nullable: true
    max_input_tokens:
      type: integer
      label: 'Max Input Tokens'
      nullable: true
    context_size:
      type: integer
      label: 'Context Size'
      nullable: true
    editor_context_ratio:
      type: float
      label: 'Editor Context Ratio'
      nullable: true
    timeout_duration:
      type: integer
      label: 'Timeout Duration'
      nullable: true
    retry_attempts:
      type: integer
      label: 'Retry Attempts'
      nullable: true
    debug_mode:
      type: boolean
      label: 'Debug Mode'
      nullable: true
    stream_content:
      type: boolean
      label: 'Stream Content'
      nullable: true
    show_error_duration:
      type: integer
      label: 'Show Error Duration'
      nullable: true
    moderation_enable:
      type: boolean
      label: 'Enable Content Moderation'
      nullable: true
    moderation_key:
      type: string
      label: 'Moderation API Key'
      nullable: true
    moderation_disable_flags:
      type: sequence
      label: 'Disabled Moderation Categories'
      nullable: true
      sequence:
        type: string
        label: 'Category'
    prompt_settings_overrides_responseRules:
      type: string
      label: 'Response Rules Override'
      nullable: true
    prompt_settings_overrides_htmlFormatting:
      type: string
      label: 'HTML Formatting Override'
      nullable: true
    prompt_settings_overrides_contentStructure:
      type: string
      label: 'Content Structure Override'
      nullable: true
    prompt_settings_overrides_tone:
      type: string
      label: 'Tone Override'
      nullable: true
    prompt_settings_overrides_inlineContent:
      type: string
      label: 'Inline Content Override'
      nullable: true
    prompt_settings_overrides_imageHandling:
      type: string
      label: 'Image Handling Override'
      nullable: true
    prompt_settings_overrides_referenceGuidelines:
      type: string
      label: 'Reference Guidelines Override'
      nullable: true
    prompt_settings_overrides_contextRequirements:
      type: string
      label: 'Context Requirements Override'
      nullable: true
    prompt_settings_additions_responseRules:
      type: string
      label: 'Response Rules Additions'
      nullable: true
    prompt_settings_additions_htmlFormatting:
      type: string
      label: 'HTML Formatting Additions'
      nullable: true
    prompt_settings_additions_contentStructure:
      type: string
      label: 'Content Structure Additions'
      nullable: true
    prompt_settings_additions_tone:
      type: string
      label: 'Tone Additions'
      nullable: true
    prompt_settings_additions_inlineContent:
      type: string
      label: 'Inline Content Additions'
      nullable: true
    prompt_settings_additions_imageHandling:
      type: string
      label: 'Image Handling Additions'
      nullable: true
    prompt_settings_additions_referenceGuidelines:
      type: string
      label: 'Reference Guidelines Additions'
      nullable: true
    prompt_settings_additions_contextRequirements:
      type: string
      label: 'Context Requirements Additions'
      nullable: true
