ckeditor_ai_agent.settings:
  type: config_object
  label: 'CKEditor AI Agent Settings'
  mapping:
    api_key:
      type: string
      label: 'API Key'
    model:
      type: string
      label: 'AI Model'
    endpoint_url:
      type: string
      label: 'Endpoint URL'
    temperature:
      type: float
      label: 'Temperature'
    max_tokens:
      type: integer
      label: 'Max Tokens'
    timeout_duration:
      type: integer
      label: 'Timeout Duration'
    retry_attempts:
      type: integer
      label: 'Retry Attempts'
    debug_mode:
      type: boolean
      label: 'Debug Mode'
    stream_content:
      type: boolean
      label: 'Stream Content'
