name: CI

on:
  push:
    branches:
      - '1.x'

permissions:
  contents: read

jobs:
  commitlint:
    name: Lint Commit Messages
    runs-on: ubicloud-standard-4
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.mjs
          helpURL: https://github.com/dxpr/ckeditor_ai_agent/blob/1.0.x/CONTRIBUTING.md

  drupal-lint:
    runs-on: ubicloud-standard-4
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - name: Lint Drupal
      run: |
        docker compose --profile lint run drupal-lint

  drupal-check:
    runs-on: ubicloud-standard-4
    steps:
    - uses: actions/checkout@v4
    - name: Drupal Deprecations and Analysis Check
      run: |
        docker compose --profile lint run drupal-check
      env:
        TARGET_DRUPAL_CORE_VERSION: 11

