name: Review

on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.mjs
          helpURL: https://github.com/dxpr/ckeditor_ai_assist/blob/1.0.x/CONTRIBUTING.md

  drupal-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3

    - name: Lint Drupal
      run: |
        docker compose run --rm drupal-lint

  drupal-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Drupal Deprecations and Analysis Check
      run: |
        docker compose run --rm drupal-check
      env:
        DRUPAL_RECOMMENDED_PROJECT: ${{ secrets.DRUPAL_RECOMMENDED_PROJECT }}
